replicaCount: 1

image:
  repository: ghcr.io/jeffkloy/usm-takehome/hello-world
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Deployment strategy for rolling updates
strategy:
  maxSurge: 1
  maxUnavailable: 0

# Revision history limit for rollbacks
revisionHistoryLimit: 10
progressDeadlineSeconds: 600

# Health check probes
probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3
  startup:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 30
